# site settings
title: Portfolio
subtitle: by HTML5 UP
email: benja.jorquera.j@gmail.com
description: Computer engineering professional portfolio
baseurl: # the subpath of your site, e.g. /blog
url: https://benjajorquera.github.io/ # the base hostname & protocol for your site
author:
street_address: Ñuñoa
city: Santiago
state: RM
zip_code: 
country: Chile
phone: (+569)93362209

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/benjajorquera
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/benjaminjorquera/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- README.md 
